--- #YAML:1.0
name:               Catalyst-Plugin-Log-Dispatch
version:            0.11
abstract:           Log module of Catalyst that uses Log::Dispatch
author:
    - Shota Takayama <shot[at]bindstorm.jp>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst:            5.65
    Log::Dispatch:       2.13
    Test::More:          0
    UNIVERSAL::require:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
